### ISSUE TITLE
Link to latest.zip  ZIP download in README not working.

### ISSUE THREAD

**Issue by nkuehn** [sphereio/sphere-category-sync#1]
If this is supposed to be just a link to the default github .ZIP  the link is  https://github.com/sphereio/sphere-category-sync/archive/master.zip  (no release branch or release tags yet)

**Comment by hajoeichler** [comment]
Yes, it's the link to the .zip file that GitHub provides. The difference to master is that the branch would contain the "compiled" JavaScript files, where as master only contains CoffeeScript files.
