### ISSUE TITLE
document usage via npm

### ISSUE THREAD

**Issue by nkuehn** [sphereio/sphere-category-sync#15]
No matter whether it's the recommended way to do in production or not  we should document the installation via npm and also link to the npm site.

**Comment by hajoeichler** [comment]
Thanks for the hint. Will adapt the README to explain how to install the component via npm.

**Comment by emmenko** [comment]
What's so difficult about `npm i sphere-category-sync`??

**Comment by nkuehn** [comment]
Nothing. It's just for consistency, most other commandlines are explicitly documented that way and the node.js overview page ( http://sphereio.github.io/nodejs/  - which I love and send out a lot)  does it that way, too.  

Basically, I'd love to see that all tools are on the overview page in a consistent way.

**Comment by emmenko** [comment]
If it's just about the overview page, you [can just add it](https://github.com/sphereio/nodejs/blob/gh-pages/assets/js/main.js#L13) :)

It wasn't published at the time I created the page.

**Comment by hajoeichler** [comment]
done, thx @emmenko to pointing me at it.

**Comment by nkuehn** [comment]
@hajoeichler thanks!  
@emmenko I was too shy ;-)
