### ISSUE TITLE
Prepare for integration with sphere-node-cli

### ISSUE THREAD

**Issue by butenkor** [sphereio/sphere-category-sync#17]
For example we should add: ```summaryReport``` to import service so that CLI can call it when streaming / processing is finished.

**Comment by emmenko** [comment]
Not quite correct: `summaryReport` is not required in the cli.

Each import type has a `finishFn` which is called when the stream has finished to process. Then it's up to the component to do whatever he wants, but there are no required functions or predefined naming conventions.

E.g.: https://github.com/sphereio/sphere-node-cli/blob/master/src/commands/import.coffee#L37

**Comment by butenkor** [comment]
So what do you suggest? Just call https://github.com/sphereio/sphere-category-sync/blob/master/src/coffee/streaming.coffee#L14 from CLI and we are done? (no summary report needed)

**Comment by emmenko** [comment]
Depends if you want to show a message at the end or not :)

**Comment by emmenko** [comment]
Usually yes. I'm just saying that it's not a requirement of the cli ;)

**Comment by butenkor** [comment]
Right. Will adapt my description ;)

**Comment by hajoeichler** [comment]
Will add a summary.

**Comment by hajoeichler** [comment]
@panshul007 we can close this, right?

**Comment by panshul007** [comment]
yes ;)
