### ISSUE TITLE
Provide a sample header file for export

### ISSUE THREAD

**Issue by svenmueller** [sphereio/sphere-category-sync#19]
Make it even simpler for everyone to export data fast.

**Comment by hajoeichler** [comment]
I guess, much easier is to allow to omit the template and then we export everything.
Only problem is the languages to use.

**Comment by hajoeichler** [comment]
With 1e68ecb08946c4ec2979d0c65ff4bdb37c72abc5 the template is optional. If not provided we will export as much as possible.
