### ISSUE TITLE
Failed to create categories as `externalId` was missing

### ISSUE THREAD

**Issue by panshul007** [sphereio/sphere-category-sync#20]
After exporting the categories from an existing project using `--parentBy id` parameter, we got a csv, with all required fields, but the externalId column was empty.
We tried to import the above csv file into another project, but it kept giving error ->  `No match found for category with external id ' '`

**Comment by svenmueller** [comment]
@panshul007 can you please add the CSV file used for the `import` command?

**Comment by panshul007** [comment]
The exported csv file and the template csv file are here: https://gist.github.com/panshul007/639d7245c487d051cd38

**Comment by hajoeichler** [comment]
@panshul007 you need to use `slug.en`.
Can you pass the template you used please to?

**Comment by panshul007** [comment]
if I use slug.en, then all the women categories do not get any slugs as all of them have slug.de
The template file is also attached in the gist. at the bottom.
