### ISSUE TITLE
`--file` parameter alias documented, but not working (only `-f` evaluated)

### ISSUE THREAD

**Issue by nkuehn** [sphereio/sphere-category-sync#26]
plus, in any case a check should be done whether an empty or undefined value is passed as file name. 

the async stack traces are not helpful btw.  Stuff that is de facto sync can be done sync, too.  Saves a mass of time in SW maintenance.

**Comment by hajoeichler** [comment]
It seems like the long arguments are broken in general.

**Comment by hajoeichler** [comment]
I opened an issue at the argument parser lib: https://github.com/bcoe/yargs/issues/255
