### ISSUE TITLE
Sorting categories by parentId

### ISSUE THREAD

**Issue by junajan** [sphereio/sphere-category-sync#44]
Currently, if you export categories and then import them back to another project you can get an error saying that a category needs its parent imported first.

This happens because categories are being imported one by one in order which is provided in CSV file which is not sorted by parents categories.

This issue can be solved if we sort output file after export or input file before import so it will have correct order (parent categories standing before their childrens)

**Comment by hisabimbola** [comment]
Fixed by #45
