### ISSUE TITLE
Improve documentation to show (or link to) valid JSON format

### ISSUE THREAD

**Issue by wizzy25** [sphereio/sphere-category-sync#47]
### EDIT:
Only documentation needs to be updated

### Description

While importing categories through json, the process fails silently if the data isn't wrapped in a ```categories``` object.

### Expected Behavior

The category should be created correctly or the documentation should state otherwise
```js
[{
  "name": {
    "en": "vehicle",
    "de": "wagen"
  },
  "slug": {
    "en": "fast",
    "de": "schnell"
  }
}]
```

### Current Behavior

Only this works, and it's not documented as such
```js
{
  "categories": [{
    "name": {
      "en": "vehicle",
      "de": "wagen"
    },
    "slug": {
      "en": "fast",
      "de": "schnell"
    }
  }]
}
```

### Context

This was tested with the Category-Import module. It could also be an issue when importing other datasets

### Possible Solution

Update the documentation accordingly or modify the code to wrap the json input in a ```categories``` object

**Comment by wizzy25** [comment]
@butenkor The supposed JSON file [schema] (https://github.com/sphereio/sphere-json-schemas/blob/master/schema/category.schema.json) redirects to a broken link.

**Comment by butenkor** [comment]
As mentioned it is not broken but still private repo :(

**Comment by butenkor** [comment]
If you are interested here link's contents (JSON schema for category import - which meant to be used for data validation before import or just as hint what structure is expected): https://gist.github.com/butenkor/660f7533c94f8eaeeb94428ac4ab9659
