### ISSUE TITLE
Sort export lines by category level per default

### ISSUE THREAD

**Issue by ValeSauer** [sphereio/sphere-category-sync#56]
When importing previously exported categories you have to provide the --sort parameter in order to prevent errors when creating categories their parents are not yet created.

Why not automatically order exported categories by category level?

**Comment by hisabimbola** [comment]
I think this was done in other to prevent breaking change (though I can't remember why we were *scared* of bumping a major version), but yeah I think sorting by default might make much sense.

Cc @junajan

**Comment by junajan** [comment]
I think we did not do it as a default parameter because it slows done the import process.

But I agree that we can do `--sort true` or `--sort` as a default and give users a possibility to turn it off by using parameter `--sort false`.

This way it will be backward compatible with current version.
