### ISSUE TITLE
Cope with unordered CSV files

### ISSUE THREAD

**Issue by hajoeichler** [sphereio/sphere-category-sync#6]
The current version can only handle ordered CSV files.
The order in this case is that a parent category must be defined before any of its child categories.

This restriction should be avoided.

**Comment by nkuehn** [comment]
+1 !

**Comment by junajan** [comment]
I created this script which will sort lines based on parentId column
https://gist.github.com/junajan/f871eb714228c54e827d2633e044e15a

**Comment by junajan** [comment]
I created this script which will sort lines based on parentId column so no child will stand before its parent.  https://gist.github.com/junajan/f871eb714228c54e827d2633e044e15a

**Comment by nkuehn** [comment]
nice, thanks.  But why a separate script?  The importer is loading the whole file into memory anyways.

**Comment by Siilwyn** [comment]
This was fixed in #e29fe9f56aca8dae5d906b61c579feb637daa91d

**Comment by nkuehn** [comment]
nice, thanks for the hint!
