### ISSUE TITLE
Comma delimiter not replaced when necessary

### ISSUE THREAD

**Issue by mat-burke** [sphereio/sphere-category-sync#67]
### Support reference number
https://jira.commercetools.com/browse/SUPPORT-3546

### Description
1. Create a Category with a Comma in its Name
2. Export Categories via IMPEX command (Property to use for referencing parent: slug)
3. Import the same Categories via IMPEX command (Property to use for referencing parent: slug)

### Expected Behavior
Categories are imported

### Current Behavior
Error message is thrown during import due to certain fields not being allowed empty content (e.g., External ID, Slug).

### Context
Unable to complete category import before manually adjusting CSV file.

### Possible Solution
Replace the comma delimiter with a semicolon in when necessary.

**Comment by Babanila** [comment]
`comma (",")` delimeter can not be used for both `the delimiter type used in the csv` and `the delimiter type used for multi value cells in the csv` when doing product import into a project ( for both old or new project).
