### ISSUE TITLE
Analyse flaky test

### ISSUE THREAD

**Issue by hajoeichler** [sphereio/sphere-category-sync#7]
It's only flaky on travis.

https://github.com/sphereio/sphere-category-sync/commit/3e9f473107cb43a087b475e4fe23b29db2c008c2

**Comment by hajoeichler** [comment]
Disabling this test didn't help!

**Comment by emmenko** [comment]
The error is pretty clear, the cleanup somehow fails

```
Streaming #constructor should initialize
   Message:
     [undefined] Error on deleting category:
NotFound: Endpoint '/import-101-64/categories/abcd942d-6b14-40c5-82ca-367c954d96c4?version=1' not found.
   Stacktrace:
     undefined
```

**Comment by hajoeichler** [comment]
Yes, but only on travis and only always the first of the integration test. I disabled the first, so the second one now fails.
