### ISSUE TITLE
Populate/read custom fields using sphere-category-sync

### ISSUE THREAD

**Issue by skyriakou** [sphereio/sphere-category-sync#73]
### Support reference number
https://jira.commercetools.com/browse/SUPPORT-4954

### Description
I'm trying to figure out how to set the custom type of my categories, and populate the custom fields of course, by way of the sync tool. I've tried a few CSV column names like "custom.type.key" but that was a random guess.

(Ideally we want to this via CSV since that's what our other current pipeline produces. But if needed, we could write a script to adapt to JSON.)

### Expected Behavior
User can populate the custom fields via CSV

**Comment by junajan** [comment]
Hello @skyriakou  .. 
please check our **price exporter** with a similar feature [here](https://commercetools.github.io/nodejs/cli/price-exporter.html#csv-headers). We can provide `customField.*` property in the CSV template which will export custom fields from prices.

I would like to use the same code for exporting custom fields also here in the category export.
```csv
name.en,slug.en,customField.simpleField,customField.ltextField.en
```

The same format will be used when importing categories. But there will have to be provided also a `customField key` which will tell us which [customFields definition](https://docs.commercetools.com/http-api-projects-custom-fields.html#customfieldsdraft) should be linked to this category.

There is one open question - I am not sure if the `category sync` from SDK knows how to sync custom fields in categories. If not we would have to implement it also there.

Please let me know if this plan is ok and I can proceed with this task. (cc @daern91)

**Comment by skyriakou** [comment]
@junajan thanks, sounds good to me - @daern91 what do you think?

**Comment by daern91** [comment]
I like this plan a lot, however, like you pointed out, I doubt that it is implemented in `category sync`. 

This should probably be two issues/implementations :-)

**Comment by junajan** [comment]
Hello @skyriakou @daern91 .. I checked the old SDK which is being used by category-sync module and it currently does not generate update actions for `custom` fields so I have to implement it there first. I created a ticket in the old SDK here:
https://github.com/sphereio/sphere-node-sdk/issues/280

**Comment by skyriakou** [comment]
@junajan can we consider this issue as done and can close it? or is anything still needed to be done? Thanks.
