### ISSUE TITLE
Permission exceeded while importing categories

### ISSUE THREAD

**Issue by Tobi-mmt** [sphereio/sphere-category-sync#87]
### Description
I want to create categories with the npm package `category-sync`. So I created a CSV with two lines 

category.csv 
```csv
"parentId","name.de-DE","slug.de-DE"
"","Damen","damen"
"damen","Taschen","taschen"
```
It works if I upload it via the browser in https://impex.commercetools.com/commands/category-import . So there should be no issue with the csv.

Now I want to upload it via the npm package with following command
```sh
.bin/category-sync import --projectKey 'xxx' --clientId 'xxx' --clientSecret 'xxx' --f category.csv --language 'de-DE' --parentBy 'slug' --continueOnProblems
```

An the following error appears:
```
{"name":"sphere-category-sync-1.2.2","hostname":"xxx","pid":xxx,"level":xxx,"data":{"body":{"statusCode":400,"message":"Permissions exceeded","errors":[{"code":"invalid_scope","message":"Permissions exceeded"}],"error":"invalid_scope","error_description":"Permissions exceeded","originalRequest":{"endpoint":"/categories?where=externalId%20in%20(%22undefined%22)&sort=id%20asc",...}
```

So it looks like the permission is not correct. But the API key gets the following permissions: `manage_products, view_published_products, view_products` like its written in the top right corner on  https://impex.commercetools.com/commands/category-import .

So in the next step I expanded the permissions for the API key. Now I added ALL permissions and executed the command with the new credentials. And it worked! 
After a couple of retrys I found out, that the required permission is `manage_project`. If this is not set, it doesn't work.

### Expected Behavior
If my API key got the `manage_products, view_published_products, view_products` it should not throw an `permission exceeded` error but should work instead.

### Current Behavior
It throws an error until you grant `manage_project` access.

### Context
I have to grant the "admin"-permission for an simple importer script. That' not what I want - because of security reasons

### Possible Solution
Sounds like a bug?

**Comment by LEQADA** [comment]
I just double checked with API docs and it seems like we there is no category targeting scope. Category is a separate resource on the platform and just referenced from a Product. So, the error seems to be reasonable.
I'd go ahead and raise a feature request on the platform level to introduce a `manage_categories` and `view_categories` scopes.

**Comment by Tobi-mmt** [comment]
Cool! Thank you @LEQADA! I look forward to hear from you if there will be a progress 🙂

**Comment by LEQADA** [comment]
@Tobi-mmt it would be better if you can describe your case to support, so they can raise the request to the platform team.

Once they add a `category` scope you can use it right away - no changes needed in this repository.
